### ISSUE TITLE
gcc6 migration tracker

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#482]
As companion to #481, here are the reverse-(build)depends on gcc6 (according to dotty on my 10.13 box):
- [x] arpack-ng (maintainer: none; this package is the only rdep of lapack361)
- [x] ccpnmr-py27 (maintainer: none; can we add newer python variants?)
- [x] gracegtk (maintainer: @akhansen, also has dep on lapack350, which is tracked in #481 as a gcc5 user)
- [x] lapack361 (maintainer: @remkos)

This can all probably be killed in short order.

**Comment by dmacks** [comment]
I'm going to work on our pile of lapackXXX libs

**Comment by dmacks** [comment]
ccpnmr is not currently policy compliant: PostInst ```UpdateAuto.py``` attempts to download and install new versions of some of its runtime files from the upstream server. PostInst ```make links``` also creates additional symlinks for some of its runtime files at that point (triggers some debian system-integrity flags) rather than having them actually in the .deb

**Comment by dmacks** [comment]
ccpnmr does not have an open license and does not even fully permit redistribution. Upstream has a new major version available that is directly downloadable ready-to-run (no compiling). Should we kill this package in fink?

**Comment by nieder** [comment]
Probably a good idea. It's unmaintained, nothing else uses it, and bad if it's breaking policy like that.

**Comment by dmacks** [comment]
Looks like we're all done here. Could someone with a clean checkout of master double-check?

**Comment by nieder** [comment]
Nothing using it, already dist-restricted.
