### ISSUE TITLE
gcc8 migration tracker

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#489]
Also need to migrate gcc8 packages to gcc9 if we want them to work on 10.15.

none
- [x] raster3d
- [x] scipy-py
- [x] tcoffee (uses systemperl; no current 10.14.5/10.15 package)
- [x] xfoil

@dhomeier (#529)
- [x] openblas

@mommsen (#496)
- [x] cernlib2006
- [x] patchy4

@nieder 
- [x] cd-hit
- [x] fasttree

@remkos 
- [x] cdo
- [x] eccodes
- [x] fftw3
- [x] grib-api-fortran
- [x] lapack380
- [x] openmpi
- [x] pgplot
- [x] netcdf-fortran7 (dist restricted to not carry forward to 10.15)
- [x] netcdf-fortran8
- [x] wip

@schwehr 
- [x] sioseis

**Comment by remkos** [comment]
Feel free to update netcdf-fortran7 to use gcc9.
I've just handed in my packages (PR #507)

**Comment by dmacks** [comment]
netcdf-fortran7 was easy to switch over, so I did it to help clean the tree.

**Comment by dmacks** [comment]
sioseis throws errors with gcc9 (I'm looking into it, but others with fortran experience are welcome to help too!)

**Comment by dhomeier** [comment]
> sioseis throws errors with gcc9 (I'm looking into it, but others with fortran experience are welcome to help too!)

Uh, `EQUIVALENCE`...!

@dmacks I managed to hack around the `IAND` exceptions with this patch (what kind of developer portal is this that does not allow `.patch` extensions?!?)
[sioseis.patch](https://github.com/fink/fink-distributions/files/3976018/sioseis.patch.txt)

Not 100 % confident it does the right thing™, but at least the tests on https://sioseis.ucsd.edu/installation.html look OK, and `mp32ieee.f`, which I am most concerned about, only seems to be relevant for the `dutil` aux program - that _appears_ to basically function as well...

**Comment by nieder** [comment]
So gcc8.4.0 was just released. It builds under 10.14 and 10.15. `sioseis` is the last gcc8 dependee.

**Comment by nieder** [comment]
Is it worth making gcc8.4.0 available to 10.15 to save a single package?

**Comment by nieder** [comment]
18ca51d1507f64836250ffa50d64036150e72dcf updates sioseis to latest that now builds cleanly with gcc9. That's the end of the gcc8 users.
