### ISSUE TITLE
openssl100 migration tracker

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#499]
Openssl 1.0.2 is the current LTS and goes EOL on 2019-12-31.
https://www.openssl.org/policies/releasestrat.html

This lists our current packages using openssl100:

none
- [ ] cargo
- [ ] qt4-base-mac
- [ ] ettercap
- [ ] re-alpine
- [ ] tor
- [ ] xar
- [ ] lynx-cur

Chris Turkel
- [ ] links

@danielj7 
- [ ] libevent2
- [ ] libserf0
- [ ] pyqt4-mac-py
- [ ] pyqt5-mac-py
- [ ] python34
- [ ] ruby20
- [ ] ruby21
- [ ] ruby22
- [ ] ruby23
- [ ] cyrus-sasl2
- [ ] postfix
- [ ] rtmpdump

@dmacks 
- [ ] elinks

@dmalloc 
- [ ] xmlsec-shlibs

@elcepi
- [ ] lynx

@fangism 
- [ ] libtorrent15
- [ ] libtorrent19
- [ ] libtorrent20

@htodd 
- [ ] alpine-alpha

Jack Fink
- [ ] libetpan-shlibs
- [ ] stone

Jesse Alama
- [ ] swi-prolog

@kamischi 
- [ ] libimobiledevice

Keith Ward
- [ ] crypt-openssl-bignum-pm
- [ ] crypt-openssl-rsa-pm

@nieder 
- [ ] dclib5
- [ ] kdelibs4
- [ ] linuxdcpp
- [ ] virtuoso

@RangerRick 
- [ ] gst-plugins-bad-0.10
- [ ] qt4-base-x11
- [ ] qt5-qtbase
- [ ] libnetsnmp30-shlibs

@TheSin- 
- [ ] php5
- [ ] libc-client1-shlibs
- [ ] apache2
- [ ] nodejs

Stefan Bruda
- [ ] mupdf

**Comment by elcepi** [comment]
I do not own a Mac anymore. Can someone take care of my packages?

**Comment by TheSin-** [comment]
I have updated for all my packages but they can't be added till my PR is since they all require tiggers, except libc-client1 and nodejs which I haven't updated yet, I'll look into them. but I feel like nodejs update will require triggers as well.

**Comment by dmacks** [comment]
In Fall'18 I looked at our of rev-dep:openssl100 packages and annotated a bunch that were going to be difficult to update: grep for "OPENSSL110 FTBFS". I tried to leave a note of whatever possibly-useful details I was able to find.

**Comment by dmacks** [comment]
For xar, see mackyle/xar#18 for openssl support and our Issue #20 for its general packaging chaos.

**Comment by dmacks** [comment]
@nieder libkf5html5-shlibs can be switched over with rev-up...same build transcript (with exception of detection/use of openssl110-dev instead of openssl100-dev)

**Comment by TheSin-** [comment]
apache2 done

**Comment by dmacks** [comment]
libevent2 is an orphaned old-libersion that FTBFS with 110; should it just be nuked altogether?

**Comment by elcepi** [comment]
Hi,

I do not have a Mac anymore. I thought I orphaned all my packages , but it
seems that I miss some. Can someone make sure that I'm not listed as a
maintainer anywhere. My email might be jhespinosa@gmail.com and
elcepi@sourceforge.net

Thanks,
Jose

**Comment by dmacks** [comment]
@elcepi I don't see you as $Maintainer of any current packages. Instead, github might be keeping you in the loop on this thread because you had participated in it previously. There's probably some way you can unsubscribe from it.

**Comment by dmacks** [comment]
> libevent2 is an orphaned old-libersion that FTBFS with 110; should it just be nuked altogether?

sent up-state

**Comment by elcepi** [comment]
No problem, I'll deal with GitHub. I just got worry that I was still listed as a mantener and want to keep me on the loop .... Thursday, 24 December 2020, 03:41PM -08:00 from Daniel Macks  notifications@github.com :

**Comment by dmacks** [comment]
Our postfix is a very old version; latest upstream supports new openssl. @danielj7 (maintainer) or someone please look into updating?

**Comment by dmacks** [comment]
Upgrading everything from cyrus-sasl2 to cyrus-sasl2.3 was easy. That old libversion is not upgradeable to openssl110, so I'll just launch it into the sun.
